spring.application.name=chatgpt-spring-api
#chatgpt api config
openai.chatgpt.url=https://api.openai.com/v1/chat/completions
openai.model=gpt-4o-mini

# Database Configuration : http://localhost:8080/h2-console
spring.datasource.url=jdbc:h2:mem:chatgpt;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
spring.datasource.driver-class-name=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
spring.jpa.hibernate.ddl-auto=update
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console



