apiVersion: v1
kind: Service
metadata:
  name: chatgpt-spring-service
  labels:
    app: chatgpt-spring-app
spec:
  type: LoadBalancer
  ports:
    - port: 8080
      targetPort: 8080
  selector:
    app: chatgpt-spring-app
